/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/10/23, 5:24 PM' 
 * Generated by 'rahee' 
 * Generated on server 'ABDUL_RAHEEM.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 OPR/102.0.0.0' 
 * Generated on web client 'http://localhost:61240/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257B9C3E017A-B9DB-46C0-A51B-1D1571E44685%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.'DM FC PRJ'n out=Work.preProcessedData;
	by 'Time Series'n;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecast forecastonly) ) out=work.outARMX1;
	identify var=UNRATE crosscorr=('Job opening'n 'federal interest rates'n);
	estimate p=(1) input=(1 $ 'Job opening'n 1 $ 'federal interest rates'n) method=ML 
		outstat=work.outstatARMX1;
	forecast lead=12 back=12 alpha=0.05 id='Time Series'n interval=month printall;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;